### ISSUE TITLE
Feature: User can post an item

### ISSUE THREAD

**Issue by paulpark330** [paulpark330/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can post an item with images, descriptions, and a location.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user clicks the 'add post' icon and the 'new post' page will slide up where he will fill out the form and submit the form.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![post-item](https://user-images.githubusercontent.com/85209433/132264207-94aef3a2-0fc9-4a10-be70-eaec4b737306.gif)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to create tables for app database
- [x] Update `data.sql` to insert a new post to the `posts` table

### ☁️ Server

- [x] Update `server/index.js` to listen for a POST request from the client
- [x] Send SQL query to the database to insert a new post
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component for the app bar
- [x] Create a  component for the header
- [x] Create a component for a new post form using FormControl from Material-UI
- [x] Create a component to upload images using Material-UI Dropzone https://github.com/Yuvaleros/material-ui-dropzone
- [x] Update user location with Geolocation API

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
