### ISSUE TITLE
Feature: User can create an account

### ISSUE THREAD

**Issue by paulpark330** [paulpark330/final-project#16]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create an account

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will fill out a form and submit it to create a new account

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/85209433/133662521-20e5ef3c-df54-4796-973e-5c81cecf0628.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to listen for a GET request from the client to the '/api/signup' route
- [x] Destructure the form data from `req.body` and has the user's password with `argon2.hash()`
- [x] Send SQL query to the database to insert the user's information into the `users` table
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to for a signup page
- [x] Use `form` to create the signup form
- [x] In the `handleSubmit`, create a new `FormData` and send a POST request to Sendbird's server
- [x] With the returned value, send a POST request to '/api/signup' route
- [x] Create a modal component to let the user know the account was created

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
