### ISSUE TITLE
Feature: User can log in and log out

### ISSUE THREAD

**Issue by paulpark330** [paulpark330/final-project#18]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can log in

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After the user has created an accout, he will be able to log in with his credentials

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/85209433/133704349-29cbc9fd-9a4c-44e3-a3c4-550aa5baebfd.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to listen for  POST request from the client to the '/api/auth/sign-in'
- [x] Destructure the form data from `req.body`
- [x] Send SQL query to the database to select userId and hashedPassword from users table 
- [x] Destructure user from the result and check for value of user
- [x] Destructure userId and hashedPassword from user and verify password with argon2
- [x] Create payload and token with jwt
- [x] Respond the the client with token and payload
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update Auth component to display the correct page depending on the route
- [x] Create handleSignIn function to send token to local storage and update the user state
- [x] Create handleSignOut function to delete token from local storage and update the user state

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
