### ISSUE TITLE
Feature: User can view item detail page

### ISSUE THREAD

**Issue by paulpark330** [paulpark330/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a single item details page

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User clicks on a post and he will be able to view the item details page

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![view-item-detail](https://user-images.githubusercontent.com/85209433/132264545-6ba1a82e-6fa1-4a6a-8555-593139b4e35d.gif)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to listen for a GET request from the client to the ‘/api/post’ route
- [x] Send SQL query to the database to select the requested post using postId
- [x] Send respond to the client containing the selected post
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component for a single item details page
- [x] Use Link component to go to the details page
- [x] Pass the data from the state from the parent `Home` component to the item details page
- [x] Display the entire page with the picture, user information, title, price, and description
- [x] Update the bottom app bar component to display the price and a button instead of nav bar

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
