### ISSUE TITLE
Feature: User authorization

### ISSUE THREAD

**Issue by paulpark330** [paulpark330/final-project#20]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User authorization

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will need to be authorized to navigate through the app

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to import authorization middleware
- [x] Modify the middleware to check for access token
- [x] If token doesn't exist, throw an error
- [x] `app.use()` should be after the two posts routes for authenticating
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update the api calls to include the token from local storage
- [x] If the api call fails, the user will be redirected to authentication page

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
