### ISSUE TITLE
Feature: User can view market

### ISSUE THREAD

**Issue by paulpark330** [paulpark330/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the market with all the items from all users

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user clicks the home icon and he will be directed to the market

## 🖼️ Wireframes

![view-selling-items](https://user-images.githubusercontent.com/85209433/132264982-e4ce4eb1-9bbe-4469-b26c-769d1f981be9.gif)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to listen for a GET request from the client to the ‘/api/home’ route
- [x] Send SQL query to the database to select all posts
- [x] Send respond to the client containing an array of all posts
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component for the home page
- [x] Display the correct page using react-router-dom
- [x] Update the header component to display the user's location
- [x] Update component to display a single post using Card from material-UI
- [x] Use Array.map() to render all Cards

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
