### ISSUE TITLE
Feature: User can search an item

### ISSUE THREAD

**Issue by paulpark330** [paulpark330/final-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search an item being sold in the market

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click the search icon and type into the search field

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/85209433/133281024-3641b8ee-00fb-446b-a38d-cb19073e5fb3.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to listen for GET request from the client to the '/api/search' route
- [x] Send SQL query to the `posts` table to select all posts where title matches the searched text
- [x] Send responce to the client containing an array of all posts
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update the header component to display the search icon in the home page
- [x] Update the header component to display the search field when the search icon is clicked
- [x] Read documentation on `req.query`
- [x] Make a GET request to the server with `req.query`
- [x] Create a component to display the search results
- [x] Update component to display a single post using Card from Material-UI
- [x] use Array.map() to render all Cards

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
