### ISSUE TITLE
Feature: User can chat with other users

### ISSUE THREAD

**Issue by paulpark330** [paulpark330/final-project#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can chat with other users

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will click on the chat icon and see a list of ongoing chats

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/85209433/133864291-40c44818-14cc-4c53-a2a0-73168569f94d.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [ ] Update `server/index.js` to listen for a POST request to the '/api/chat' route
- [ ] Send a SQL query to insert a new chat to the chats table
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Use Sendbird's UIKit to integrate their chat API
- [ ] Add an onClick to the chat button
- [ ] Extract userId for both buyer and seller
- [ ] If the post is made by the user, the bottom button should be 'edit' instead of 'chat'
- [ ] Send a POST request to Sendbird's server to start a new chat

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
